main: me.victorum.victorum.Victorum
name: Victorum
version: 1.0.0
author: Juubes
webite: https://victorum.me/
load: STARTUP
depend:
- Vault
load-before:
- Vault
commands:
  claim:
    aliases:
    - faction
    - f
  balance:
    aliases:
    - bal
    - money
  baltop: null